[package]
name = "tovarus"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.4.11", features = ["derive", "env"] }
csv = "1.3.0"
shell-escape = "0.1.5"
thiserror = "1.0.50"
